import type { IncomeType, LoanType } from '../types'

export const RULES = {
  lenderFoir: {
    salaried: 0.55,
    self_employed: 0.45,
    informal: 0.35,
    mixed: 0.40,
  } satisfies Record<IncomeType, number>,
  safeFoir: {
    salaried: 0.35,
    self_employed: 0.28,
    informal: 0.22,
    mixed: 0.25,
  } satisfies Record<IncomeType, number>,
  lowScorePenalty: {
    threshold: 700,
    lenderFoirDelta: -0.05,
    safeFoirDelta: -0.03,
  },
  highCostDebt: {
    aprThresholdPct: 24,
    safeFoirDelta: -0.02,
  },
  foirBounds: {
    lenderMin: 0.20,
    lenderMax: 0.60,
    safeMin: 0.15,
    safeMax: 0.40,
  },
  veryGoodScore: 775,
  productRouting: {
    securedBusinessMinCollateral: 1000000,
    twoWheelerMaxAmount: 500000,
  },
  incomeAssessment: {
    selfEmployedItrHighMultiplier: 1.10,
    selfEmployedNoItrLowShare: 0.65,
    selfEmployedNoItrHighShare: 0.80,
    informalLowShare: 0.60,
    informalHighShare: 0.75,
    mixedLowShare: 0.80,
    mixedHighShare: 0.90,
  },
  pricing: {
    goodScoreThreshold: 750,
    rateFloorPct: 7,
    minimumBandWidthPct: 1,
    veryGoodScore: { lowDelta: -0.5, highDelta: -2.5 },
    goodScore: { lowDelta: 0, highDelta: -1.0 },
    lowScore: { lowDelta: 2.0, highDelta: 4.0 },
    unknownScore: { lowDelta: -0.5, highDelta: 2.5 },
    shortEmploymentYears: 1,
    stableEmploymentYears: 3,
    shortEmployment: { lowDelta: 0.5, highDelta: 1.5 },
    stableEmployment: { lowDelta: 0, highDelta: -0.5 },
    shortBusinessYears: 2,
    stableBusinessYears: 5,
    shortBusiness: { lowDelta: 0.5, highDelta: 1.5 },
    stableBusiness: { lowDelta: 0, highDelta: -0.5 },
    cardUtilisationMediumThreshold: 50,
    cardUtilisationHighThreshold: 75,
    mediumCardUtilisation: { lowDelta: 0, highDelta: 1.0 },
    highCardUtilisation: { lowDelta: 1.0, highDelta: 2.0 },
    informalIncome: { lowDelta: 2.5, highDelta: 5.0 },
    selfEmployedNoItr: { lowDelta: 1.5, highDelta: 3.0 },
    recentBounce: { lowDelta: 3.0, highDelta: 5.0 },
    securedBusinessCollateral: { lowDelta: -0.5, highDelta: -0.5 },
  },
  minimumTenureMonths: 12,
  maxRepaymentAge: {
    personal: 60,
    business_secured: 70,
    business_unsecured: 65,
    two_wheeler: 65,
    home: 70,
    lap: 70,
    gold: 70,
    auto_recommend: 60,
  } satisfies Record<LoanType, number>,
  recentBounce: {
    lenderFoirDelta: -0.10,
    hardStopWithHighCostDebt: true,
  },
  emergencySavings: {
    strongMonths: 6,
    safeFoirBonus: 0.03,
    weakMonths: 1,
    safeFoirPenalty: -0.03,
  },
  dependantPenalty: {
    threshold: 2,
    safeFoirDelta: -0.02,
  },
  minimumResidualBuffer: {
    shareOfIncome: 0.20,
    rupeeFloor: 15000,
  },
  unknownDebtProxy: {
    monthlyShareOfHighCostOutstanding: 0.08,
    monthlyShareOfConservativeIncome: 0.10,
  },
  unknownHouseholdExpenseProxy: {
    shareOfConservativeIncome: 0.50,
    rupeeFloor: 15000,
  },
  uncertainty: {
    baseWidthPct: 0.08,
    widthPerMissingSignalPct: 0.018,
    maxWidthPct: 0.30,
    highConfidenceMaxWidthPct: 0.11,
    mediumConfidenceMaxWidthPct: 0.18,
  },
  rounding: {
    amountRangeStep: 5000,
    recommendedAmountStep: 5000,
    emiCeilingStep: 500,
    displayedEmiStep: 100,
  },
  distressPossibleLenderOfferCap: 75000,
  stress: {
    incomeDropPct: 0.20,
  },
  collateralLtv: {
    business_secured: 0.65,
    lap: 0.60,
    gold: 0.75,
  },
  tenureMonths: {
    personal: 60,
    business_secured: 120,
    business_unsecured: 60,
    two_wheeler: 48,
    home: 240,
    lap: 120,
    gold: 24,
    auto_recommend: 60,
  } satisfies Record<LoanType, number>,
  productAmountCaps: {
    personal: 2500000,
    business_secured: 50000000,
    business_unsecured: 5000000,
    two_wheeler: 500000,
    home: 50000000,
    lap: 50000000,
    gold: 5000000,
    auto_recommend: 2500000,
  } satisfies Record<LoanType, number>,
  defaultFeesPct: {
    personal: { low: 0.5, high: 2.0 },
    business_secured: { low: 0.5, high: 1.0 },
    business_unsecured: { low: 1.0, high: 2.5 },
    two_wheeler: { low: 1.0, high: 3.0 },
    home: { low: 0.25, high: 1.0 },
    lap: { low: 0.5, high: 1.5 },
    gold: { low: 0.25, high: 1.0 },
    auto_recommend: { low: 0.5, high: 2.0 },
  } satisfies Record<LoanType, { low: number; high: number }>,
  gstOnProcessingFee: 0.18,
} as const

export const BASE_RATE_BANDS: Record<LoanType, { low: number; high: number }> = {
  personal: { low: 11.0, high: 15.0 },
  business_secured: { low: 9.5, high: 13.0 },
  business_unsecured: { low: 13.0, high: 20.0 },
  two_wheeler: { low: 11.0, high: 18.0 },
  home: { low: 8.0, high: 10.5 },
  lap: { low: 9.0, high: 12.5 },
  gold: { low: 8.5, high: 13.0 },
  auto_recommend: { low: 11.0, high: 16.0 },
}
